#!/usr/bin/env node
/**
 * Daily blog post generator.
 * Runs at 10:00 Europe/Berlin via scheduled agent.
 *
 * Looks at git activity from the previous 24h, drafts a DE+EN blog post
 * summarizing what shipped, appends to blog/posts.json, regenerates the feed.
 *
 * Public visibility: skips anything under docs/ (work-in-progress notes).
 *
 * The actual prose is generated by the calling agent (Claude) — this script
 * gathers the raw signal and writes the files. The agent fills in title,
 * teaser, and post body.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const SKIP_PATHS = ['docs/', '.claude/', 'logs/', 'tests/'];

function gitlog(since) {
  const fmt = '%H%x09%s';
  return execSync(
    `git log --since="${since}" --pretty=format:"${fmt}" --no-merges`,
    { cwd: REPO, encoding: 'utf8' }
  )
    .trim()
    .split('\n')
    .filter(Boolean)
    .map(line => {
      const [hash, subject] = line.split('\t');
      return { hash, subject };
    });
}

function filesChanged(since) {
  const out = execSync(
    `git log --since="${since}" --name-only --pretty=format: --no-merges`,
    { cwd: REPO, encoding: 'utf8' }
  );
  const files = [...new Set(out.split('\n').filter(Boolean))];
  return files.filter(f => !SKIP_PATHS.some(p => f.startsWith(p)));
}

function gatherSignal() {
  const since = '24 hours ago';
  const commits = gitlog(since);
  const files = filesChanged(since);
  const publicFiles = files.filter(f =>
    f.endsWith('.html') || f.endsWith('.css') || f.endsWith('.js') || f.endsWith('.json') || f.endsWith('.svg')
  );
  return { commits, files, publicFiles };
}

if (require.main === module) {
  const signal = gatherSignal();
  console.log(JSON.stringify(signal, null, 2));
}

module.exports = { gatherSignal };
