#!/usr/bin/env python3
"""
import-artifacts.py — Stefan's Claude-Artefakt-Import-Skript

Liest Artefakt-Dateien aus einem Quell-Ordner (Default: ~/Downloads/),
filtert sie auf wahrscheinliche Anthropic-Artefakte, kopiert sie nach
docs/imported-artifacts/ (gitignored), erstellt einen INDEX.md.

Verwendung:
    python3 scripts/import-artifacts.py
    python3 scripts/import-artifacts.py --src ~/Desktop/anthropic-exports
    python3 scripts/import-artifacts.py --src ~/Downloads --since-days 7

Sicher:
- Kopiert (nicht verschiebt) — Originale in Quell-Ordner bleiben unverändert.
- Schreibt nur nach docs/imported-artifacts/ (gitignored).
- Schreibt keine globalen Files an.
- Tut nichts, wenn Quell-Ordner nicht existiert.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import os
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEST_DIR = REPO_ROOT / "docs" / "imported-artifacts"

# File extensions we consider artifact-worthy
ARTIFACT_EXTS = {".html", ".htm", ".md", ".txt", ".json", ".js", ".jsx", ".tsx",
                 ".ts", ".py", ".css", ".svg", ".vue", ".react", ".yaml", ".yml"}

# Filename patterns that strongly suggest a Claude/Anthropic artifact
ARTIFACT_NAME_PATTERNS = [
    re.compile(r"artifact[-_]?", re.IGNORECASE),
    re.compile(r"claude[-_]", re.IGNORECASE),
    re.compile(r"anthropic[-_]", re.IGNORECASE),
    # UUID-style names like 7399e576-6161-4210-84d6-996838e4c674
    re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.IGNORECASE),
]

# Content markers — substrings that strongly suggest the file came from Claude
CONTENT_MARKERS = [
    "claude.ai",
    "anthropic",
    "<!-- Generated by Claude",
    "<!-- Anthropic",
    "data-claude-",
]


def looks_like_artifact(path: Path) -> tuple[bool, str]:
    """Return (is_artifact, reason)."""
    if path.suffix.lower() not in ARTIFACT_EXTS:
        return False, f"extension {path.suffix} not in allowlist"

    name = path.name
    for pat in ARTIFACT_NAME_PATTERNS:
        if pat.search(name):
            return True, f"filename matches /{pat.pattern}/"

    # Peek at content for marker strings (read first 4 KB only)
    try:
        with path.open("rb") as f:
            head = f.read(4096).decode("utf-8", errors="ignore").lower()
        for marker in CONTENT_MARKERS:
            if marker.lower() in head:
                return True, f"content contains '{marker}'"
    except Exception as e:
        return False, f"read error: {e}"

    # If file is reasonably sized (1 KB – 5 MB) and one of the artifact-typical
    # extensions, take it. Stefan said "alle" — be generous.
    try:
        size = path.stat().st_size
    except OSError:
        return False, "stat failed"
    if 1024 <= size <= 5 * 1024 * 1024:
        return True, f"plausible-size {size}-byte {path.suffix} file"

    return False, f"size {size} outside 1KB–5MB range"


def short_hash(path: Path) -> str:
    """First 8 chars of SHA-256 of contents (for collision-free renaming)."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()[:8]


def safe_dest_name(src: Path) -> str:
    """Build a stable, conflict-free destination filename."""
    stem = re.sub(r"[^a-zA-Z0-9_.-]+", "-", src.stem)[:80]
    digest = short_hash(src)
    return f"{stem}__{digest}{src.suffix.lower()}"


def first_line_summary(path: Path) -> str:
    """Return a 200-char summary: first non-empty line of textual content."""
    try:
        with path.open("r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                stripped = line.strip()
                # skip empty / pure tag-only / comment-only lines
                if not stripped:
                    continue
                if stripped.startswith("<!") or stripped.startswith("//"):
                    continue
                # strip HTML tags for summary
                cleaned = re.sub(r"<[^>]+>", " ", stripped)
                cleaned = re.sub(r"\s+", " ", cleaned).strip()
                if cleaned:
                    return cleaned[:200]
        return "[empty or tag-only file]"
    except Exception as e:
        return f"[read error: {e}]"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path, default=Path.home() / "Downloads",
                        help="Quell-Ordner (default: ~/Downloads)")
    parser.add_argument("--since-days", type=int, default=None,
                        help="Nur Dateien neuer als N Tage importieren")
    parser.add_argument("--dry-run", action="store_true",
                        help="Zeige was gemacht würde, kopiere nichts")
    args = parser.parse_args()

    src: Path = args.src.expanduser().resolve()
    if not src.exists() or not src.is_dir():
        print(f"❌ Quell-Ordner nicht gefunden: {src}", file=sys.stderr)
        sys.exit(1)

    print(f"📂 Quelle:   {src}")
    print(f"📂 Ziel:     {DEST_DIR}")
    print(f"🧪 Dry-run:  {args.dry_run}")
    print()

    if not args.dry_run:
        DEST_DIR.mkdir(parents=True, exist_ok=True)

    cutoff = None
    if args.since_days is not None:
        cutoff = dt.datetime.now() - dt.timedelta(days=args.since_days)
        print(f"⏰ Filter:   nur Dateien neuer als {cutoff.isoformat()}")

    candidates = sorted(src.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)

    found = []
    skipped = []

    for path in candidates:
        if not path.is_file():
            continue

        if cutoff is not None:
            mtime = dt.datetime.fromtimestamp(path.stat().st_mtime)
            if mtime < cutoff:
                continue

        is_art, reason = looks_like_artifact(path)
        if not is_art:
            skipped.append((path.name, reason))
            continue

        dest_name = safe_dest_name(path)
        dest = DEST_DIR / dest_name
        summary = first_line_summary(path)

        if dest.exists():
            print(f"⏭  bereits importiert: {path.name} → {dest_name}")
            continue

        if args.dry_run:
            print(f"   würde kopieren: {path.name} → {dest_name}")
            print(f"   Grund: {reason}")
            print(f"   Vorschau: {summary}")
        else:
            shutil.copy2(path, dest)
            print(f"✓  {path.name} → {dest_name}")

        found.append({
            "src": path,
            "dest": dest,
            "size": path.stat().st_size,
            "mtime": dt.datetime.fromtimestamp(path.stat().st_mtime).isoformat(timespec="seconds"),
            "reason": reason,
            "summary": summary,
        })

    print()
    print(f"✓  {len(found)} importiert")
    print(f"⏭  {len(skipped)} übersprungen")

    if found and not args.dry_run:
        # Write/append INDEX.md
        index_path = DEST_DIR / "INDEX.md"
        existing = ""
        if index_path.exists():
            existing = index_path.read_text(encoding="utf-8")

        new_block = ["", f"## Import-Lauf {dt.datetime.now().isoformat(timespec='minutes')}", ""]
        new_block.append(f"Quelle: `{src}`")
        new_block.append(f"Importiert: {len(found)} Dateien")
        new_block.append("")
        new_block.append("| Original | Im Repo | Größe | mtime | Grund | Vorschau |")
        new_block.append("|---|---|---|---|---|---|")
        for f in found:
            preview = f["summary"].replace("|", "\\|")[:140]
            new_block.append(
                f"| `{f['src'].name}` | `{f['dest'].name}` | {f['size']} B | {f['mtime']} | {f['reason']} | {preview} |"
            )
        new_block.append("")

        if not existing:
            header = [
                "# Imported Artifacts — Index",
                "",
                "Dateien, die per `scripts/import-artifacts.py` aus parallelen Quellen",
                "(Anthropic-Web-Exports, andere Claude-Sessions, Downloads) importiert",
                "wurden. Liegt in `docs/imported-artifacts/`, ist gitignored.",
                "",
                "Stefan reviewt manuell, integriert ausgewählte Inhalte in",
                "`/journeys/` oder andere Site-Bereiche, wenn passend.",
                "",
            ]
            index_path.write_text("\n".join(header) + "\n".join(new_block) + "\n",
                                  encoding="utf-8")
        else:
            index_path.write_text(existing.rstrip() + "\n" + "\n".join(new_block) + "\n",
                                  encoding="utf-8")

        print(f"📝 Index aktualisiert: {index_path}")

    if skipped:
        print()
        print("Übersprungen (erste 10):")
        for name, reason in skipped[:10]:
            print(f"   {name} — {reason}")
        if len(skipped) > 10:
            print(f"   ...und {len(skipped) - 10} weitere")


if __name__ == "__main__":
    main()
